#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Faster R-CNN (all-weather) training with:
- Param groups LR (smaller LR for backbone) + LR drop at unfreeze
- Early Stopping by mAP50-95
- Grad clipping + Gradient accumulation
- Optional AMP (--no_amp to disable)
- Backbone freeze/unfreeze
- RPN/ROI downscale to save memory
- YOLO -> COCO conversion (once)
- COCO info/licenses fallback for pycocotools
- Val uses batch_size=1 to save VRAM

Outputs:
  outdir/
    annotations/all_train.json, all_val.json
    best.pth
    metrics.json
    results.csv  (mAP50, mAP50_95, p50_ms, p95_ms)
"""

import argparse, json, subprocess, time
from pathlib import Path
import numpy as np
from PIL import Image

import torch, torchvision
import torch.nn.utils as nn_utils
from torch.utils.data import DataLoader
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.transforms import functional as F

# ---- AMP compatibility (torch>=2.4 prefers torch.amp, fallback to torch.cuda.amp)
use_new_amp = False
try:
    from torch import amp as _amp_mod  # type: ignore[attr-defined]
    use_new_amp = True
except Exception:
    pass

def make_scaler(enabled: bool):
    if use_new_amp:
        try:
            return _amp_mod.GradScaler('cuda', enabled=enabled)  # positional for older minor versions
        except TypeError:
            return _amp_mod.GradScaler(enabled=enabled)
    else:
        from torch.cuda.amp import GradScaler as _GS  # type: ignore
        return _GS(enabled=enabled)

class _AutoCastCtx:
    def __init__(self, enabled: bool):
        self.enabled = enabled
    def __enter__(self):
        if use_new_amp:
            self.ctx = _amp_mod.autocast('cuda', enabled=self.enabled)
        else:
            from torch.cuda.amp import autocast as _ac  # type: ignore
            self.ctx = _ac(enabled=self.enabled)
        return self.ctx.__enter__()
    def __exit__(self, *args):
        return self.ctx.__exit__(*args)

# --------------------------- Dataset ---------------------------
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval

class CocoDet(torch.utils.data.Dataset):
    def __init__(self, ann_file, transforms=None):
        self.coco = COCO(ann_file)
        self.ids = list(self.coco.imgs.keys())
        self.transforms = transforms
    def __getitem__(self, idx):
        img_id = self.ids[idx]
        info = self.coco.loadImgs([img_id])[0]
        img = Image.open(info["file_name"]).convert("RGB")
        ann_ids = self.coco.getAnnIds(imgIds=[img_id])
        anns = self.coco.loadAnns(ann_ids)
        boxes, labels, areas, crowds = [], [], [], []
        for a in anns:
            x, y, w, h = a["bbox"]
            if w <= 0 or h <= 0: continue
            boxes.append([x, y, x + w, y + h])
            labels.append(int(a["category_id"]))
            areas.append(float(a.get("area", w*h)))
            crowds.append(int(a.get("iscrowd", 0)))
        tgt = {
            "boxes": torch.as_tensor(boxes, dtype=torch.float32),
            "labels": torch.as_tensor(labels, dtype=torch.int64),
            "image_id": torch.tensor([img_id]),
            "area": torch.as_tensor(areas, dtype=torch.float32),
            "iscrowd": torch.as_tensor(crowds, dtype=torch.int64),
        }
        if self.transforms: img = self.transforms(img)
        return img, tgt
    def __len__(self): return len(self.ids)

def collate_fn(batch):
    imgs, tars = list(zip(*batch))
    return list(imgs), list(tars)

# --------------------------- Eval & Latency ---------------------------
@torch.no_grad()
def evaluate_coco(model, ann_file, device, score_thresh=0.001, num_workers=4):
    model.eval()
    ds = CocoDet(ann_file, transforms=F.to_tensor)
    # Val batch=1 to save VRAM
    dl = DataLoader(ds, batch_size=1, shuffle=False, num_workers=num_workers, collate_fn=collate_fn)

    coco = ds.coco
    img_ids = ds.ids
    results = []

    # Fallback for pycocotools expecting these keys
    coco.dataset.setdefault('info', {'description': 'generated by yolo2coco', 'version': '1.0'})
    coco.dataset.setdefault('licenses', [])

    for images, targets in dl:
        images = [img.to(device) for img in images]
        outputs = model(images)
        for out, tgt in zip(outputs, targets):
            img_id = int(tgt["image_id"].item())
            boxes = out["boxes"].detach().cpu().numpy()
            scores = out["scores"].detach().cpu().numpy()
            labels = out["labels"].detach().cpu().numpy()
            keep = scores >= score_thresh
            boxes, scores, labels = boxes[keep], scores[keep], labels[keep]
            for b, s, c in zip(boxes, scores, labels):
                x1,y1,x2,y2 = b.tolist()
                results.append({
                    "image_id": img_id,
                    "category_id": int(c),
                    "bbox": [float(x1), float(y1), float(x2-x1), float(y2-y1)],
                    "score": float(s)
                })

    if not results:
        return {"mAP50_95": 0.0, "mAP50": 0.0}

    cocoDt = coco.loadRes(results)
    ev = COCOeval(coco, cocoDt, "bbox")
    ev.params.imgIds = img_ids
    ev.evaluate(); ev.accumulate(); ev.summarize()
    return {"mAP50_95": float(ev.stats[0]), "mAP50": float(ev.stats[1])}

@torch.no_grad()
def measure_latency(model, ann_file, device, runs=100):
    ds = CocoDet(ann_file, transforms=F.to_tensor)
    ids = ds.ids[:runs] if runs < len(ds) else ds.ids
    times = []
    model.eval()
    for img_id in ids:
        info = ds.coco.loadImgs([img_id])[0]
        img = F.to_tensor(Image.open(info["file_name"]).convert("RGB")).to(device)
        if torch.cuda.is_available(): torch.cuda.synchronize()
        t0 = time.time()
        _ = model([img])
        if torch.cuda.is_available(): torch.cuda.synchronize()
        times.append((time.time()-t0)*1000.0)
    if not times: return {"p50_ms": float("nan"), "p95_ms": float("nan")}
    t = np.array(times, dtype=np.float64)
    return {"p50_ms": float(np.percentile(t, 50)), "p95_ms": float(np.percentile(t, 95))}

# --------------------------- Helpers ---------------------------
def set_backbone_trainable(model, trainable: bool):
    for _, p in model.backbone.named_parameters():
        p.requires_grad = trainable

def yolo_to_coco_once(images_dir: Path, labels_dir: Path, names_yaml: Path, out_json: Path, yolo2coco_script: Path):
    if out_json.exists(): return
    out_json.parent.mkdir(parents=True, exist_ok=True)
    cmd = ["python", str(yolo2coco_script),
           "--images_dir", str(images_dir),
           "--labels_dir", str(labels_dir),
           "--names_yaml", str(names_yaml),
           "--out_json", str(out_json)]
    subprocess.check_call(cmd)

# --------------------------- Main ---------------------------
def main():
    ap = argparse.ArgumentParser()
    # data
    ap.add_argument("--dataset_root", default="datasets/bdd_yolo/all")
    ap.add_argument("--names_yaml", default="yamls/bdd_all.yaml")
    ap.add_argument("--yolo2coco_script", default="scripts/yolo2coco.py")
    # train
    ap.add_argument("--epochs", type=int, default=24)
    ap.add_argument("--batch_size", type=int, default=2)
    ap.add_argument("--lr", type=float, default=0.0025)
    ap.add_argument("--weight_decay", type=float, default=5e-4)
    ap.add_argument("--num_workers", type=int, default=8)
    ap.add_argument("--accum_steps", type=int, default=1)
    ap.add_argument("--grad_clip", type=float, default=10.0)
    ap.add_argument("--frozen_epochs", type=int, default=0)
    # LR controls for stability
    ap.add_argument("--bb_lr_scale", type=float, default=0.25, help="backbone LR scale vs head")
    ap.add_argument("--lr_after_unfreeze_mult", type=float, default=0.5, help="multiply all LRs when unfreezing")
    # AMP toggle
    ap.add_argument("--no_amp", action="store_true", help="disable AMP if set")
    # early stopping
    ap.add_argument("--early_stop_patience", type=int, default=5)
    ap.add_argument("--early_stop_delta", type=float, default=1e-4)
    # misc
    ap.add_argument("--outdir", default="results/frcnn_all")
    ap.add_argument("--resume", default=None)
    ap.add_argument("--eval_only", action="store_true")
    ap.add_argument("--latency_runs", type=int, default=200)
    # image size
    ap.add_argument("--min_size", type=int, default=800)
    ap.add_argument("--max_size", type=int, default=1333)
    args = ap.parse_args()

    outdir = Path(args.outdir); outdir.mkdir(parents=True, exist_ok=True)
    ann_dir = outdir / "annotations"; ann_dir.mkdir(exist_ok=True)

    # 1) YOLO -> COCO (only once)
    img_train = Path(args.dataset_root)/"images"/"train"
    lab_train = Path(args.dataset_root)/"labels"/"train"
    img_val   = Path(args.dataset_root)/"images"/"val"
    lab_val   = Path(args.dataset_root)/"labels"/"val"
    ann_train = ann_dir/"all_train.json"
    ann_val   = ann_dir/"all_val.json"
    yolo_to_coco_once(img_train, lab_train, Path(args.names_yaml), ann_train, Path(args.yolo2coco_script))
    yolo_to_coco_once(img_val, lab_val, Path(args.names_yaml), ann_val, Path(args.yolo2coco_script))

    # 2) Datasets & loaders
    train_ds = CocoDet(str(ann_train), transforms=F.to_tensor)
    val_ds   = CocoDet(str(ann_val),   transforms=F.to_tensor)
    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True,
                              num_workers=args.num_workers, collate_fn=collate_fn)
    # (val loader not strictly needed; evaluate_coco builds its own with bs=1)

    # 3) Model
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    num_classes = len(train_ds.coco.cats) + 1  # + background
    model = torchvision.models.detection.fasterrcnn_resnet50_fpn_v2(weights="DEFAULT")
    # replace head
    in_feats = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = FastRCNNPredictor(in_feats, num_classes)
    # resize policy (saves memory vs default 800/1333 if you pass 640/1024)
    model.transform.min_size = (args.min_size,)
    model.transform.max_size = args.max_size
    # ↓↓↓ RPN/ROI downscale to reduce VRAM & spiky grads — version-safe ↓↓↓
    rpn = model.rpn

    def _maybe_set(obj, name, value):
        if hasattr(obj, name):
            try:
                setattr(obj, name, value)
                return True
            except Exception:
                return False
        return False

    tuned = False

    # Case A: 新版是 dict 风格（不可调用）
    pre_attr = getattr(rpn, "pre_nms_top_n", None)
    post_attr = getattr(rpn, "post_nms_top_n", None)
    if isinstance(pre_attr, dict) and isinstance(post_attr, dict):
        try:
            rpn.pre_nms_top_n["training"]  = 1000
            rpn.pre_nms_top_n["testing"]   = 600
            rpn.post_nms_top_n["training"] = 1000
            rpn.post_nms_top_n["testing"]  = 300
            tuned = True
        except Exception:
            tuned = False

    # Case B: 老版本是“方法”，内部读 *_train / *_test（不要覆盖方法本身！）
    if callable(getattr(rpn, "pre_nms_top_n", None)) or callable(getattr(rpn, "post_nms_top_n", None)):
        setA = _maybe_set(rpn, "pre_nms_top_n_train", 1000)
        setB = _maybe_set(rpn, "pre_nms_top_n_test",  600)
        setC = _maybe_set(rpn, "post_nms_top_n_train",1000)
        setD = _maybe_set(rpn, "post_nms_top_n_test", 300)
        tuned = tuned or (setA or setB or setC or setD)

    # Case C: 极少数版本只有单值属性（训练/测试共用）
    if (not tuned) and isinstance(pre_attr, (int, float)) and isinstance(post_attr, (int, float)):
        tuned |= _maybe_set(rpn, "pre_nms_top_n",  1000)
        tuned |= _maybe_set(rpn, "post_nms_top_n", 300)

    if not tuned:
        print("[WARN] Could not modify RPN top-N; keeping defaults.")

    # ROI: 不同版本字段名可能不同
    roi_tuned = False
    if hasattr(model.roi_heads, "batch_size_per_image"):
        model.roi_heads.batch_size_per_image = 256
        roi_tuned = True
    elif hasattr(model.roi_heads, "box_batch_size_per_image"):
        model.roi_heads.box_batch_size_per_image = 256
        roi_tuned = True
    if not roi_tuned:
        print("[WARN] ROI batch_size_per_image field not found; keeping default.")
    # ↑↑↑ end RPN/ROI downscale ↑↑↑

    # move
    model.to(device)

    # Optimizer with param groups (smaller LR for backbone)
    bb_params = [p for _, p in model.backbone.named_parameters()]
    other_params = [p for n, p in model.named_parameters() if not n.startswith("backbone")]
    optimizer = torch.optim.SGD(
        [{"params": bb_params, "lr": args.lr * args.bb_lr_scale},
         {"params": other_params, "lr": args.lr}],
        momentum=0.9, weight_decay=args.weight_decay
    )
    lr_sch = torch.optim.lr_scheduler.StepLR(optimizer, step_size=max(1, args.epochs//3), gamma=0.1)

    # AMP scaler
    use_amp = torch.cuda.is_available() and (not args.no_amp)
    scaler = make_scaler(enabled=use_amp)

    # Resume
    ckpt_best = outdir/"best.pth"
    best_map5095 = -1.0
    start_epoch = 1
    if args.resume and Path(args.resume).exists():
        ckpt = torch.load(args.resume, map_location="cpu")
        model.load_state_dict(ckpt["model"])
        optimizer.load_state_dict(ckpt["optim"])
        start_epoch = int(ckpt.get("epoch", 1)) + 1
        best_map5095 = float(ckpt.get("metrics", {}).get("mAP50_95", -1.0))
        print(f"[OK] resumed from {args.resume}")

    # Optional freeze backbone for first N epochs
    if args.frozen_epochs > 0:
        set_backbone_trainable(model, False)
        print(f"[Freeze] backbone frozen for first {args.frozen_epochs} epochs")

    # Train
    if not args.eval_only:
        no_improve = 0
        accum = max(1, args.accum_steps)
        for ep in range(start_epoch, args.epochs + 1):
            model.train()
            running = 0.0
            optimizer.zero_grad(set_to_none=True)

            # Unfreeze & drop LR at the moment of unfreezing
            if args.frozen_epochs > 0 and ep == args.frozen_epochs + 1:
                set_backbone_trainable(model, True)
                for g in optimizer.param_groups:
                    g["lr"] *= args.lr_after_unfreeze_mult
                print(f"[Unfreeze] backbone unfrozen; "
                      f"bb_lr={optimizer.param_groups[0]['lr']:.6f}, "
                      f"head_lr={optimizer.param_groups[1]['lr']:.6f}")

            for it, (images, targets) in enumerate(train_loader, start=1):
                images = [img.to(device) for img in images]
                targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

                with _AutoCastCtx(enabled=use_amp):
                    loss_dict = model(images, targets)
                    loss = sum(loss_dict.values()) / accum

                # NaN/Inf guard
                if not torch.isfinite(loss):
                    bad = {k: float(v.detach().item()) for k, v in loss_dict.items()}
                    print(f"[WARN] non-finite loss at iter {it}: {bad}. Skipping this batch.")
                    optimizer.zero_grad(set_to_none=True)
                    continue

                scaler.scale(loss).backward()

                if it % accum == 0:
                    scaler.unscale_(optimizer)
                    nn_utils.clip_grad_norm_(model.parameters(), max_norm=args.grad_clip)
                    scaler.step(optimizer)
                    scaler.update()
                    optimizer.zero_grad(set_to_none=True)

                running += float(loss.item()) * accum

            lr_sch.step()
            avg_loss = running / max(1, len(train_loader))
            print(f"[Train] epoch {ep}/{args.epochs}  loss={avg_loss:.4f}")

            # Validate
            metrics = evaluate_coco(model, str(ann_val), device=device, num_workers=args.num_workers)
            cur = metrics["mAP50_95"]
            print(f"[Val] mAP50_95={metrics['mAP50_95']:.4f}  mAP50={metrics['mAP50']:.4f}")

            # Save best & early stopping
            if cur > best_map5095 + args.early_stop_delta:
                best_map5095 = cur
                no_improve = 0
                torch.save({"model": model.state_dict(),
                            "optim": optimizer.state_dict(),
                            "epoch": ep, "metrics": metrics}, ckpt_best)
                print(f"[OK] saved best -> {ckpt_best}")
            else:
                no_improve += 1
                print(f"[ES] no improvement {no_improve}/{args.early_stop_patience}")
                if no_improve >= args.early_stop_patience:
                    print("[ES] early stopping triggered.")
                    # do not break immediately; we already saved best
                    break

    # Final eval on best
    if ckpt_best.exists():
        ckpt = torch.load(ckpt_best, map_location="cpu")
        model.load_state_dict(ckpt["model"])
        print(f"[OK] loaded best for final eval: {ckpt_best}")

    final_m = evaluate_coco(model, str(ann_val), device=device, num_workers=args.num_workers)
    final_lat = measure_latency(model, str(ann_val), device=device, runs=args.latency_runs)
    print(f"[Final] mAP50_95={final_m['mAP50_95']:.4f}  mAP50={final_m['mAP50']:.4f}  "
          f"p50={final_lat['p50_ms']:.2f}ms  p95={final_lat['p95_ms']:.2f}ms")

    outdir.joinpath("results.csv").write_text(
        "mAP50,mAP50_95,p50_ms,p95_ms\n{:.6f},{:.6f},{:.3f},{:.3f}\n".format(
            final_m["mAP50"], final_m["mAP50_95"], final_lat["p50_ms"], final_lat["p95_ms"]
        ), encoding="utf-8"
    )
    outdir.joinpath("metrics.json").write_text(json.dumps({**final_m, **final_lat}, indent=2), encoding="utf-8")

if __name__ == "__main__":
    main()
